import React from 'react';

function KeyAdvantages() {
  return (
    <div className='w-full max-w-[1230px] mx-auto text-center pb-16 px-4'>
      <h1 className='text-3xl font-bold text-[#48e463]'>Key Advantages</h1>
      <div className='flex items-end justify-end w-full pt-5 pb-2'>
      <div className='md:flex hidden justify-around gap-2 items-center md:w-2/5 '>
      <h1 className='text-center font-bold text-xl'>$SMRT</h1>
      <h1></h1>
      <h1 className='text-center font-bold text-xl'>Traditional Crypto Coins</h1>
      </div>
      </div>
      <div className='flex flex-col md:flex-row items-start text-left'>
        <div className='md:w-2/5 w-full'>
          <h1 className='text-xl font-semibold'>Use Case</h1>
          <p className='text-xl mt-1'>$SMRT token can be used for:</p>
          <ul className='ml-6 text-lg list-disc'>
            <li>SMRT Online Store</li>
            <li>Vesting</li>
            <li>Staking</li>
            <li>Investment</li>
          </ul>
          <p className='text-lg mt-10'>Join us as we embark on this new chapter, driven by our vision of a brighter, more sustainable tomorrow.</p>
        </div>.
        <div className='flex md:hidden justify-between gap-2 items-center w-full'>
      <h1 className='text-center font-bold text-lg'>$SMRT</h1>
      <h1></h1>
      <h1 className='text-center font-bold text-lg'>Traditional Crypto Coins</h1>
      </div>
        <div className='md:w-3/5 w-full bg-[#5ddf73be] rounded-xl flex flex-col justify-between items-start gap-4 p-2 mt-6 md:mt-0'>
          <div className='flex sm:flex-row flex-col w-full justify-between gap-4 border-b pb-2'>
            <h2 className='text-lg sm:w-1/3 font-semibold text-black'>• Price Control</h2>
            <h2 className='text-lg sm:w-2/5'>Real-world projects to keep price stable</h2>
            <h2 className='text-lg sm:w-1/3'>Price is not stable</h2>
          </div>
          <div className='flex sm:flex-row flex-col  w-full justify-between gap-4 border-b pb-4'>
            <h2 className='text-lg sm:flex-row flex-col sm:w-1/3 font-semibold text-black'>• Volatility</h2>
            <h2 className='text-lg sm:w-2/5'>Low volatility</h2>
            <h2 className='text-lg sm:w-1/3'>Uncontrollable volatility</h2>
          </div>
          <div className='flex sm:flex-row flex-col  w-full justify-between gap-4 border-b pb-4'>
            <h2 className='text-lg sm:w-1/3 font-semibold text-black'>• Low Risk </h2>
            <h2 className='text-lg sm:w-2/5'>Controllable Risk </h2>
            <h2 className='text-lg sm:w-1/3'>Extreme Risk</h2>
          </div>
          <div className='flex sm:flex-row flex-col  w-full justify-between gap-4 border-b pb-4'>
            <h2 className='text-lg sm:w-1/3 font-semibold text-black'>• Outside Incomes</h2>
            <h2 className='text-lg sm:w-2/5'>Revenue is generated by real-world projects</h2>
            <h2 className='text-lg sm:w-1/3'>No outside source of revenue</h2>
          </div>
          <div className='flex sm:flex-row flex-col  w-full justify-between gap-4 pb-2'>
            <h2 className='text-lg sm:w-1/3 font-semibold text-black'>• Locked in Period</h2>
            <h2 className='text-lg sm:w-2/5'>No lockup time</h2>
            <h2 className='text-lg sm:w-1/3'>Fixed times to try to overcome the inflation issue</h2>
          </div>
        </div>
      </div>
    </div>
  );
}

export default KeyAdvantages;
